route: 
  receiver: 'email-receiver'
  repeat_interval: 4h
  group_by: [alertname]

receivers: 
  - name: 'email-receiver'
    email_configs: 
      - smarthost: 'smtp.gmail.com:587'
        auth_username: '{{SMTP_AUTH_USERNAME}}'
        auth_password: '{{SMTP_AUTH_PASSWORD}}'
        from: '{{SMTP_AUTH_USERNAME}}'
        to: '{{SMTP_AUTH_RECEIVER_EMAIL}}'
        require_tls: true
