services:
  scoring-service:
    build:
      context: .
      dockerfile: "Scoring Service/Dockerfile"
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Javid@123
      - MSSQL_PID=Developer 
    volumes:
      - sqlserver_data:/var/opt/mssql

  prometheus:
    build: 
      context: .
      dockerfile: dockerfile-prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
      - source: prometheus_alert_rules_config
        target: /etc/prometheus/alert_rules.yml
    depends_on:
      - scoring-service

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"  
    volumes:
      - grafana_data:/var/lib/grafana 
    depends_on:
      - prometheus

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    restart: unless-stopped
    volumes:
      - alertmanager_data:/alertmanager/data
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/alertmanager.yml
    environment:
      - SMTP_AUTH_USERNAME=${SMTP_AUTH_USERNAME}
      - SMTP_AUTH_PASSWORD=${SMTP_AUTH_PASSWORD}
      - SMTP_AUTH_RECEIVER_EMAIL=${SMTP_AUTH_RECEIVER_EMAIL}
    depends_on:
      - prometheus

volumes:
  sqlserver_data:
  prometheus_data:
  grafana_data:
  alertmanager_data:

configs:
  prometheus_config:
    file: ./prometheus.yml
  prometheus_alert_rules_config: 
    file: ./alert_rules.yml
  alertmanager_config:
    file: ./alertmanager.yml