services:
  scoring-service:
    build:
      context: .
      dockerfile: "Scoring Service/Dockerfile"
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Javid@123
      - MSSQL_DATABASE=scoringdb
    volumes:
      - sqlserver_data:/var/opt/mssql

  prometheus:
    build: 
      context: .
      dockerfile: dockerfile-prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    depends_on:
      - scoring-service

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"  
    volumes:
      - grafana_data:/var/lib/grafana 
    depends_on:
      - prometheus

volumes:
  sqlserver_data:
  prometheus_data:
  grafana_data:

configs:
  prometheus_config:
    file: ./prometheus.yml