global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - 'alert_rules.yml'

alerting: 
  alertmanagers: 
    - scheme: http
      static_configs:
        - targets: 
            - alertmanager.default.svc.cluster.local:9093

scrape_configs:
  - job_name: "scoring-service"
    static_configs:
      - targets: ["scoring-service.default.svc.cluster.local:5001"]