apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
{{ .Files.Get "files/prometheus.yml" | indent 3 }}
  alert_rules.yml: |
{{.Files.Get "files/alert_rules.yml" | indent 3 }}